apiVersion: apps/v1
kind: Deployment
metadata:
  name: trust-score-api
  labels:
    app: trust-score
spec:
  replicas: 3
  selector:
    matchLabels:
      app: trust-score
  template:
    metadata:
      labels:
        app: trust-score
    spec:
      containers:
        - name: trust-score-api
          image: your-dockerhub-username/trust-score-api:latest
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_URL
              value: "postgresql://admin:password@trust-db-service:5432/trustdb"
            - name: REDIS_URL
              value: "redis://trust-cache-service:6379/0"
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: trust-score-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8000
  selector:
    app: trust-score
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: trust-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trust-db
  template:
    metadata:
      labels:
        app: trust-db
    spec:
      containers:
        - name: postgres
          image: postgres:15
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: "admin"
            - name: POSTGRES_PASSWORD
              value: "password"
            - name: POSTGRES_DB
              value: "trustdb"
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: db-storage
      volumes:
        - name: db-storage
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: trust-db-service
spec:
  type: ClusterIP
  ports:
    - port: 5432
  selector:
    app: trust-db
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: trust-cache
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trust-cache
  template:
    metadata:
      labels:
        app: trust-cache
    spec:
      containers:
        - name: redis
          image: redis:7
          ports:
            - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: trust-cache-service
spec:
  type: ClusterIP
  ports:
    - port: 6379
  selector:
    app: trust-cache
